sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: mysql2.sqlpub.com
    port: 3307
    database: wuwei_sky_take_out
    username: ww_sky_take_out
    password: 1Qc5VstpbEOh3PxY
